import streamlit as st
import os
import pandas as pd
from pandas_gbq import read_gbq
from google.oauth2 import service_account

creds_dict = st.secrets["gcp_service_account"]
credentials = service_account.Credentials.from_service_account_info(creds_dict)

project_id = "ts2g-462411"

query_deps = """
SELECT * FROM `ts2g-462411.dataset.table`
"""

df_deps = read_gbq(query_deps, project_id=project_id, credentials=credentials)
[gcp_service_account]
type = "service_account"
project_id = "ts2g-462411"
private_key_id = "3becc6c5f1f564799048e55c6f6d2197b934b9a6"
private_key = ""-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/QQUN2M/6jFWs\nW20hVLW3XcsMhDmcCYJ4rNy/fJTr06dNaeNYyY2WFkB73+l8ZjCspOZoziB2WbfJ\n1msqBcYuPHBQu231vQrTjwt/J56MDAPkAiV0R5hY/kIP06eVk4RUAG78Cnb3cL0c\n7gwUXzgN5IBaXzEPF6A1iOOY4McJR9mCK0387MYFFaQ10mDJoCthGmF3ZYxgLq3T\nTJsiZqIF/HzacZVC1SbknQDzblYnRMfeMQaoTin+M824Gbc8ZWNV0Uqie2P1zaHx\n2VuOP2FQnrMPUClQ+Hg9a2z3XSsBEn05wzfC5rrTz6RTWiL7oVLeMYfahrLMXaHd\nmP+OQOTvAgMBAAECggEAIb4McLl4VBlvQhXtRoyl9MB5Au/PJC7vVHAXEDegJI02\nfqt4X2FL+Bdb8B78mCSFYOhE+GephYflq5gHVyYmpWCnZi7zQwBDyTh7DEeGqumx\nxAf26LF6+PR+3kD216ZrmdBrxE7qV1SOIO0Et5FnF9hhJtCVnLaL3vYURZQeuY2k\nBkwMed/cf8FBrpE+Vovo4aO0LvXcTQxJo9+L9M48z98LTr3p/ceUG8BjrGPdb3fj\nAR8OvCgULO16Kc8OmISqrma2HVXSRk9kGhAJ6pUgknfBstDU4vu7n2HJTzCbu7J+\n4KDfjl7MLc8IOcx749cG+yeeeI5hV7ABMq08KOOPIQKBgQDgJG+ndS6UULIb8boG\ndeg2p5IINmI3rbVDpyt41mlgrcaN7FwLbmu+vtCsZDMqOfblbg0MG/bqzzcReidh\nVPRWfiuQfp8xykzAtcNBTECrH39rcHjHmA53mEa8umgvyFYCjXkOI9jkHVPzy6rL\nliH+P6M1KX4TR7m4tzbmhUHMYQKBgQDab+t6pj7BicBkIB5PjJpsDNLM1cNk7Z7q\nqVR+I5nDnfqMZfWNHQJP11IxlRNM4wjzV5iscVVeW3bWoI5DLr1JZS7jLTGcm5Bp\n0huHCBXeBUbRr/G5eClSdoGbqLSqLjQPADU2qvJfTnkqL1nAwZIWaVbFBXsi4F82\nD+l60OuzTwKBgQCxLlxMxacCex+wU084GDBuM9yOPV86oEgvqJAGv4chc30HZ5YD\nO1BUwkX2YGbJtHRlPK93qQtw5kijuiozGJLlZGtPl6iEFWTC2Wv1zC86lnWFGq1/\nKcYV5/vS6I+/ZeAHuIm/Ebs756sbhx4GPTG159w+BASzfPlk+P+fDivLQQKBgAdQ\nC+AVRLCR/gDcGmerW1gWrc/xsBLm6ZUNiiiW5ITp+wNMPoY03Gjz2mqShQzj5N7Q\npenP+X2pLjdNNLYHEIsuef1c+/Y0Nwdz4zwIB0NhhddrPnppDWkXUot1gGbaGSAP\nb7iezHJoXCIPZ7/OOyfI6wC5iD/IpydWLQjRibJ9AoGBANCIFpO/Flpva/dJTtAj\nAuya1h/HMUlPYQQbWIuL96yFSgqHGSkmc5dnBxv0kg3cRCNgD3P/57ivfr7G53H8\nQH66Ue23zYDEIKUg7Bu5o5xNx2xWpuI5lV24gGEC8cH/gCrudhubenL/fJR55BJE\nPNmwkNsMXgSi54smvGvRbN7J\n-----END PRIVATE KEY-----\n",
client_email = "streamlit-access@ts2g-462411.iam.gserviceaccount.com"
client_id = "116269582593801031066"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40ts2g-462411.iam.gserviceaccount.com"