[gcp_service_account]
type = "service_account"
project_id = "ts2g-462411"
private_key_id = "16bda31a860adb89dcc11cccfa935d3a1f877ace"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChNy6KkP7gF6Xx
iAmxo5yTbwskA5ZHwjN+aClDZShFvcFTrj/OgDMFr3JSB6oxCHwsP0/ChII0Pvbm
RMKo9WuTFlxhWhPqeVTX+QHiiJNV7ER3Cdve2ELM3fyI6Oceebjkl1UXShIdJ0KI
kmcFPn4Xst0GeBrF+B/5Ako/nIdCiWK6LPUDDRX5XCR+ZF+cSPfMQxPgArR08V6e
seSln8x0I0eNX+GhGBVsyquh9/Y72+BJi/NFo24TgqsK8XRrJ5cMzmkwpv65xGh2
NDIEco4UeWxsVg8xlvkjhfiS+2qyqiZjcjxit0OXe5wj6GVTwOOYrxnzNRD5YJSa
09En+92lAgMBAAECggEAIbwUEVtXdimEqDbE/obDyicjn+jfPstQrqwZrFhj1boo
FPxirjGt24vzwl4Hu0RxBWpHJKdJPqkJTbSIPkZCuS/l61onzjoO6rWYsyBMol9z
ESy/NVGwIsH16OlBiaNDcRQIsnulsDOJrN3j0FlcFdXwAb1Kru/lstvLkSWOOToE
5/sWoUNaLthRIM+IVOX5Z3zJPMuJhVRDNwktccMW2xPxIFa+WrGRQMRLO476ni0a
Xc73nMUck299M2XYviXswwi61orbOWAdZWz9BbKSHLtpL0JV2at44+jfWDvTts7Y
LpI63sdfWo5+/4ajIPS32+xJzXVOt3RhcX2p35YEkQKBgQDND1pqN0h3nckytZoI
KodoNqyt5JQZrn6qCZup2BjWOXgFG03lieBRN8OjJ/ajKqJ9XpMdVNdcXZX3/7Nu
/cUkcT1gz8yKE1457jeDwV/vQ887cLXELXWi+kKZOcfTTognUfCJyanbBnE+lJ01
HafP9ePRVxgQxJ84HOtPzznasQKBgQDJQ5K684epRRDXsbuwjyM1g82hiMf21M6t
yCh9z4KN200QkgWdLXArxIJFRj2/X2PHfXeuoJfZmtsNLnnhV+LMCz/B3KDoj5TN
nS5s9cFcLkudUhV092I6XOuX9vTcTdHKxfO1uXfsEgL8dMnDrpgcnfFFsW8evbT0
PKBYJKLHNQKBgQCdRAcdquRjCJoD0A8f8C4FGNl6S/HheFggZFoD+n2h3lVT5Urq
ncFxyIi8GqwnG02fROci+axpZETd/DdLCkkl18sw8m11/8CmQTJGVAoVYDYQ6jId
EJhFtBVbmlrMjlARh+AobIdeOSSk0Cl5URMghP6B0H/ebE2IJXW6sb03IQKBgQDA
pyM0O1r3h7oYjfQYjNtqJXFXl8O5nXj9VmSUEWdp/KrnGq+vBciizKbaQuNmZZvw
YESI7waL8LSQCJX4Q5VANeBg5J1OH+qTa0r+V7wwTcxpmiIZ5ZesQDfwLh+zJfaU
wCmKITAO1Crxl6Vu35iRhApo6PByH6uwQrxFw0PhpQKBgCTEyrSuvHz9Fnw6FII5
R+B74l0YIdQM/ZERlnVAYc/kBw8a6F/rSsjInF+4CHd57Bq8hTLFBfz6k2uzQ9L8
YL26Cjo1a1F8jrmlF7JsTYSG8US09La5rXMviYamw5Rq2cxmmqymBECY6QqlkH1e
JqDoZWow3kEIODuYd5NQwO/w
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@ts2g-462411.iam.gserviceaccount.com"
client_id = "103366247012711132919"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40ts2g-462411.iam.gserviceaccount.com"
universe_domain = "googleapis.com"